name: Build Nightly
on:
  push:
    branches: [ devel ]
    tags:
      - 'nightly'
jobs:
  build:
    strategy:
      matrix:
        os:
        - name: ubuntu
          version: latest
        - name: windows
          version: latest
        - name: macos
          version: latest
    runs-on: ${{ matrix.os.name }}-${{ matrix.os.version }}

    steps:
    - uses: actions/checkout@v2
    - name: Init
      run: |
        mkdir bass/obj
        mkdir bass/out
        mkdir dist
        cp -R bass/data/* bass/out/
        cp -R doc bass/out/
    
    - name: Make
      run: make
      working-directory: bass      

    - name: Pack
      uses: papeloto/action-zip@v1
      with:
        files: bass/out/
        dest: dist/bass-${{ matrix.os.name }}.zip

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: bass-${{ matrix.os.name }}
        path: dist/bass*.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download
      uses: actions/download-artifact@v2
      with:
        path: dist
    
    - name: Crunch down files
      run: |
        find . -name \*.zip -exec cp {} . \;
      working-directory: dist
    
    - uses: "marvinpinto/action-automatic-releases@v1.2.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly"
        title: "Development Build"
        prerelease: true
        files: dist/bass-*.zip
